name: BlockSniffer
author: DRedDogPE
description: Trace block interaction!
version: 1.0.0
main: BlockSniffer\Main
api: [3.0.0-ALPHA12]
commands:
  bs:
    description: Use /bs here
    permission: blocksniffer
permissions:
  blocksniffer:
    default: true
    description: "Allows the use of /bs here"
